### ISSUE TITLE
Signed apk not working

### ISSUE THREAD

**Issue by Abhinandnandu** [zfdang/android-multiple-images-selector#30]
Process: codmob.com.campuswalletTeacherApp, PID: 28105
    java.lang.InternalError
        at e.d.d.b.y.a(Unknown Source:14)
        at e.d.d.b.h.<clinit>(Unknown Source:4)
        at e.d.d.a.a(Unknown Source:6)
        at e.d.d.a.<init>(Unknown Source:16)
        at e.d.d.a.<init>(Unknown Source:3)
        at e.d.d.d$1.<init>(Unknown Source:0)
        at e.d.d.d.<clinit>(Unknown Source:76)
        at e.a.a(Unknown Source:0)
        at com.zfdang.multiple_images_selector.ImagesSelectorActivity.LoadFolderAndImages(Unknown Source:34)
        at com.zfdang.multiple_images_selector.ImagesSelectorActivity.requestReadStorageRuntimePermission(Unknown Source:22)
        at com.zfdang.multiple_images_selector.ImagesSelectorActivity.onCreate(Unknown Source:231)

**Comment by vaibhav936** [comment]
Can you find any solution yet ?
